# ai_agents/master_agent/router.py
import json
from typing import Dict, Any, List
from langgraph.graph import StateGraph, START, END
from ai_agents.state import AgentState
from ai_agents.master_agent.prompts import MASTER_AGENT_SYSTEM_PROMPT
from ai_agents.llm_gateway import LLMGateway

class MasterRouter:
    """
    ProjectMaster LangGraph Orchestrator. 
    Interprets user intent and routes to sub-agents (Schedule, WBS, Resource).
    """
    def __init__(self):
        self.llm = LLMGateway()
        self._build_graph()

    def _build_graph(self):
        builder = StateGraph(AgentState)

        # Map nodes
        builder.add_node("intent_recognition", self._node_recognize_intent)
        builder.add_node("plan_execution", self._node_execute_plan)
        builder.add_node("human_fallback", self._node_fallback_to_human)
        
        # Define edges
        builder.add_edge(START, "intent_recognition")
        
        # Conditional Edge routing
        builder.add_conditional_edges(
            "intent_recognition",
            self._route_intent,
            {
                "execute": "plan_execution",
                "missing_info": "human_fallback"
            }
        )

        builder.add_edge("plan_execution", END)
        builder.add_edge("human_fallback", END)

        self.graph = builder.compile()

    def _node_recognize_intent(self, state: AgentState) -> Dict[str, Any]:
        """Uses LLM to classify user message according to prompt JSON schema."""
        messages = [
            {"role": "system", "content": MASTER_AGENT_SYSTEM_PROMPT},
        ]
        messages.extend(state.get("messages", []))

        # Explicitly ask LLM for JSON format as required by prompt
        response_text = self.llm.chat_completion(
             messages=messages, 
             temperature=0.1
        )
        
        try:
            # Clean possible markdown wrap ` ```json `
            json_text = response_text.replace('```json', '').replace('```', '').strip()
            parsed_intent = json.loads(json_text)
            
            return {
                "current_intent": parsed_intent.get("intent_summary", "Unknown"),
                "requires_multi_step": parsed_intent.get("requires_multi_step", False),
                "execution_plan": parsed_intent.get("execution_plan", []),
                "context_data": {
                    "missing_information": parsed_intent.get("missing_information", []),
                    "reply": parsed_intent.get("reply_to_user", "")
                }
            }
        except json.JSONDecodeError:
             return {
                 "context_data": {
                     "missing_information": [],
                     "reply": f"Internal Error: Failed to parse Agent Intent JSON. Raw: {response_text}"
                 }
             }

    def _route_intent(self, state: AgentState) -> str:
        """Determines next node based on identified intent properties."""
        context = state.get("context_data", {})
        if context.get("missing_information"):
            return "missing_info"
        
        if state.get("execution_plan"):
             return "execute"
             
        # Ultimate fallback
        return "missing_info"

    def _node_execute_plan(self, state: AgentState) -> Dict[str, Any]:
        """Executes the sub-agents sequentially. (Placeholder for now)"""
        plan = state.get("execution_plan", [])
        results = f"Simulated Execution of {len(plan)} steps.\n"
        
        for step in plan:
             results += f"- Executed {step.get('target_agent')} for action: {step.get('action')}\n"
             
        return {
            "final_response": results
        }
        
    def _node_fallback_to_human(self, state: AgentState) -> Dict[str, Any]:
        """Returns the clarifying questions generated by the LLM."""
        reply = state.get("context_data", {}).get("reply", "I lack some context to proceed.")
        return {
            "final_response": reply
        }

    def process(self, messages: List[Dict[str, str]]) -> str:
        """Entrypoint for the API router to call."""
        initial_state: AgentState = {
            "messages": messages,
            "project_id": "DEFAULT",
            "current_intent": "",
            "requires_multi_step": False,
            "execution_plan": [],
            "current_step_index": 0,
            "context_data": {},
            "final_response": ""
        }
        
        # Invoke LangGraph
        final_state = self.graph.invoke(initial_state)
        return final_state.get("final_response", "No response generated.")
